pipeline {
    agent any
    libraries {
        lib "jk_shared_library@main"
    }
    parameters {
        string(name: 'DB_NAME', defaultValue: '', description: 'Database name to deploy SQL code')
        string(name: 'SCHEMA_NAME', defaultValue: '', description: 'Schema managed by Flyway')
        string(name: 'DB_CONNECTION', defaultValue: '', description: 'JDBC URL for PostgreSQL DB connection')
        choice name: 'ACTION', choices: ['Info', 'Baseline', 'Migrate']
        string(name: 'VERSION', defaultValue: '', description: 'Flyway deployment file version')
    }
    stages {
        stage('Retrieve Vault Credentials') {
            steps {
                script {
                    def credentials = retrieveVaultCredentials(
                    dbName: params.DB_NAME,
                    schemaName: params.SCHEMA_NAME
                    )
                    env.DB_USERNAME = credentials.username
                    env.DB_PASSWORD = credentials.password
                }
            }
        }
        stage('Deploy Database') {
            agent {
                docker {
                    image 'flyway/flyway:latest'
                }
            }
            steps {
                script {
                    sh """
                        shared-library/${env.FLYWAY_SHELL_SCRIPT} \
                            --db_connection="${params.DB_CONNECTION}" \
                            --schema_name="${params.SCHEMA_NAME}" \
                            --version="${params.VERSION}"
                    """
                }
            }
        }
    }
}
